# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(663, 535)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 461))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.zbid = QtGui.QWidget()
        self.zbid.setObjectName(_fromUtf8("zbid"))
        self.frame = QtGui.QFrame(self.zbid)
        self.frame.setGeometry(QtCore.QRect(70, 50, 481, 341))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.listWidget_zbid = QtGui.QListWidget(self.frame)
        self.listWidget_zbid.setGeometry(QtCore.QRect(10, 40, 461, 241))
        self.listWidget_zbid.setObjectName(_fromUtf8("listWidget_zbid"))
        item = QtGui.QListWidgetItem()
        self.listWidget_zbid.addItem(item)
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 68, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 121, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(310, 10, 101, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(100, 10, 20, 21))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(263, 10, 20, 21))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton_zbidRefresh = QtGui.QPushButton(self.frame)
        self.pushButton_zbidRefresh.setGeometry(QtCore.QRect(350, 300, 121, 27))
        self.pushButton_zbidRefresh.setObjectName(_fromUtf8("pushButton_zbidRefresh"))
        self.tabWidget.addTab(self.zbid, _fromUtf8(""))
        self.zbstumbler = QtGui.QWidget()
        self.zbstumbler.setObjectName(_fromUtf8("zbstumbler"))
        self.tabWidget.addTab(self.zbstumbler, _fromUtf8(""))
        self.zbwireshark = QtGui.QWidget()
        self.zbwireshark.setObjectName(_fromUtf8("zbwireshark"))
        self.tabWidget.addTab(self.zbwireshark, _fromUtf8(""))
        self.zbdump = QtGui.QWidget()
        self.zbdump.setObjectName(_fromUtf8("zbdump"))
        self.tabWidget.addTab(self.zbdump, _fromUtf8(""))
        self.zbreplay = QtGui.QWidget()
        self.zbreplay.setObjectName(_fromUtf8("zbreplay"))
        self.tabWidget.addTab(self.zbreplay, _fromUtf8(""))
        self.zbpanidconflictflood = QtGui.QWidget()
        self.zbpanidconflictflood.setObjectName(_fromUtf8("zbpanidconflictflood"))
        self.tabWidget.addTab(self.zbpanidconflictflood, _fromUtf8(""))
        self.zborphannotify = QtGui.QWidget()
        self.zborphannotify.setObjectName(_fromUtf8("zborphannotify"))
        self.tabWidget.addTab(self.zborphannotify, _fromUtf8(""))
        self.zbrealign = QtGui.QWidget()
        self.zbrealign.setObjectName(_fromUtf8("zbrealign"))
        self.tabWidget.addTab(self.zbrealign, _fromUtf8(""))
        self.zbfakebeacon = QtGui.QWidget()
        self.zbfakebeacon.setObjectName(_fromUtf8("zbfakebeacon"))
        self.tabWidget.addTab(self.zbfakebeacon, _fromUtf8(""))
        self.zbopenear = QtGui.QWidget()
        self.zbopenear.setObjectName(_fromUtf8("zbopenear"))
        self.tabWidget.addTab(self.zbopenear, _fromUtf8(""))
        self.zbassocflood = QtGui.QWidget()
        self.zbassocflood.setObjectName(_fromUtf8("zbassocflood"))
        self.tabWidget.addTab(self.zbassocflood, _fromUtf8(""))
        self.zbconvert = QtGui.QWidget()
        self.zbconvert.setObjectName(_fromUtf8("zbconvert"))
        self.tabWidget.addTab(self.zbconvert, _fromUtf8(""))
        self.zbdsniff = QtGui.QWidget()
        self.zbdsniff.setObjectName(_fromUtf8("zbdsniff"))
        self.tabWidget.addTab(self.zbdsniff, _fromUtf8(""))
        self.zbgoodfind = QtGui.QWidget()
        self.zbgoodfind.setObjectName(_fromUtf8("zbgoodfind"))
        self.tabWidget.addTab(self.zbgoodfind, _fromUtf8(""))
        self.zbwardrive = QtGui.QWidget()
        self.zbwardrive.setObjectName(_fromUtf8("zbwardrive"))
        self.tabWidget.addTab(self.zbwardrive, _fromUtf8(""))
        self.zbscapy = QtGui.QWidget()
        self.zbscapy.setObjectName(_fromUtf8("zbscapy"))
        self.tabWidget.addTab(self.zbscapy, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTools = QtGui.QAction(MainWindow)
        self.actionTools.setObjectName(_fromUtf8("actionTools"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionTools)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Attify Zigbee Exploitation Tool", None))
        __sortingEnabled = self.listWidget_zbid.isSortingEnabled()
        self.listWidget_zbid.setSortingEnabled(False)
        self.listWidget_zbid.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Device", None))
        self.label_2.setText(_translate("MainWindow", "Product String", None))
        self.label_3.setText(_translate("MainWindow", "Serial Number", None))
        self.pushButton_zbidRefresh.setText(_translate("MainWindow", "Refresh Devices", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbid), _translate("MainWindow", "zbid", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbstumbler), _translate("MainWindow", "zbstumbler", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbwireshark), _translate("MainWindow", "zbwireshark", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbdump), _translate("MainWindow", "zbdump", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbreplay), _translate("MainWindow", "zbreplay", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbpanidconflictflood), _translate("MainWindow", "zbpanidconflictflood", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zborphannotify), _translate("MainWindow", "zborphannotify", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbrealign), _translate("MainWindow", "zbrealign", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbfakebeacon), _translate("MainWindow", "zbfakebeacon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbopenear), _translate("MainWindow", "zbopenear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbassocflood), _translate("MainWindow", "zbassocflood", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbconvert), _translate("MainWindow", "zbconvert", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbdsniff), _translate("MainWindow", "zbdsniff", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbgoodfind), _translate("MainWindow", "zbgoodfind", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbwardrive), _translate("MainWindow", "zbwardrive", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbscapy), _translate("MainWindow", "zbscapy", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "Settings", None))
        self.actionTools.setText(_translate("MainWindow", "Tools", None))
        self.actionTools.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

