# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(663, 535)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 461))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.zbid = QtGui.QWidget()
        self.zbid.setObjectName(_fromUtf8("zbid"))
        self.frame = QtGui.QFrame(self.zbid)
        self.frame.setGeometry(QtCore.QRect(70, 50, 481, 341))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.listWidget_zbid = QtGui.QListWidget(self.frame)
        self.listWidget_zbid.setGeometry(QtCore.QRect(10, 40, 461, 241))
        self.listWidget_zbid.setObjectName(_fromUtf8("listWidget_zbid"))
        item = QtGui.QListWidgetItem()
        self.listWidget_zbid.addItem(item)
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 68, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 121, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(310, 10, 101, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(100, 10, 20, 21))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(263, 10, 20, 21))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.pushButton_zbidRefresh = QtGui.QPushButton(self.frame)
        self.pushButton_zbidRefresh.setGeometry(QtCore.QRect(350, 300, 121, 27))
        self.pushButton_zbidRefresh.setObjectName(_fromUtf8("pushButton_zbidRefresh"))
        self.tabWidget.addTab(self.zbid, _fromUtf8(""))
        self.zbstumbler = QtGui.QWidget()
        self.zbstumbler.setObjectName(_fromUtf8("zbstumbler"))
        self.textEdit_zbstmblrConsole = QtGui.QTextEdit(self.zbstumbler)
        self.textEdit_zbstmblrConsole.setGeometry(QtCore.QRect(10, 60, 621, 351))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.textEdit_zbstmblrConsole.setPalette(palette)
        self.textEdit_zbstmblrConsole.setReadOnly(True)
        self.textEdit_zbstmblrConsole.setObjectName(_fromUtf8("textEdit_zbstmblrConsole"))
        self.pushButton_zbstmblrStart = QtGui.QPushButton(self.zbstumbler)
        self.pushButton_zbstmblrStart.setGeometry(QtCore.QRect(530, 20, 99, 27))
        self.pushButton_zbstmblrStart.setObjectName(_fromUtf8("pushButton_zbstmblrStart"))
        self.checkBox_zbstmblrVerbose = QtGui.QCheckBox(self.zbstumbler)
        self.checkBox_zbstmblrVerbose.setGeometry(QtCore.QRect(410, 20, 99, 31))
        self.checkBox_zbstmblrVerbose.setObjectName(_fromUtf8("checkBox_zbstmblrVerbose"))
        self.comboBox_zbstmblrChannel = QtGui.QComboBox(self.zbstumbler)
        self.comboBox_zbstmblrChannel.setGeometry(QtCore.QRect(160, 20, 91, 27))
        self.comboBox_zbstmblrChannel.setObjectName(_fromUtf8("comboBox_zbstmblrChannel"))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.comboBox_zbstmblrChannel.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.zbstumbler)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.zbstumbler, _fromUtf8(""))
        self.zbwireshark = QtGui.QWidget()
        self.zbwireshark.setObjectName(_fromUtf8("zbwireshark"))
        self.frame_3 = QtGui.QFrame(self.zbwireshark)
        self.frame_3.setGeometry(QtCore.QRect(20, 30, 601, 381))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.lineEdit_zbwscount = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_zbwscount.setGeometry(QtCore.QRect(250, 190, 111, 27))
        self.lineEdit_zbwscount.setObjectName(_fromUtf8("lineEdit_zbwscount"))
        self.pushButton_zbwsStart = QtGui.QPushButton(self.frame_3)
        self.pushButton_zbwsStart.setGeometry(QtCore.QRect(220, 270, 141, 27))
        self.pushButton_zbwsStart.setCheckable(True)
        self.pushButton_zbwsStart.setObjectName(_fromUtf8("pushButton_zbwsStart"))
        self.lineEdit_zbwsInterface = QtGui.QLineEdit(self.frame_3)
        self.lineEdit_zbwsInterface.setGeometry(QtCore.QRect(250, 90, 113, 27))
        self.lineEdit_zbwsInterface.setObjectName(_fromUtf8("lineEdit_zbwsInterface"))
        self.comboBox_zbwsChannel = QtGui.QComboBox(self.frame_3)
        self.comboBox_zbwsChannel.setGeometry(QtCore.QRect(250, 140, 111, 27))
        self.comboBox_zbwsChannel.setObjectName(_fromUtf8("comboBox_zbwsChannel"))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.comboBox_zbwsChannel.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(170, 140, 68, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(170, 86, 68, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(170, 190, 68, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.tabWidget.addTab(self.zbwireshark, _fromUtf8(""))
        self.zbdump = QtGui.QWidget()
        self.zbdump.setObjectName(_fromUtf8("zbdump"))
        self.frame_2 = QtGui.QFrame(self.zbdump)
        self.frame_2.setGeometry(QtCore.QRect(20, 30, 601, 381))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(170, 86, 68, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_zbdumpInterface = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_zbdumpInterface.setGeometry(QtCore.QRect(250, 90, 113, 27))
        self.lineEdit_zbdumpInterface.setObjectName(_fromUtf8("lineEdit_zbdumpInterface"))
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(170, 140, 68, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox_zbdumpChannel = QtGui.QComboBox(self.frame_2)
        self.comboBox_zbdumpChannel.setGeometry(QtCore.QRect(250, 140, 111, 27))
        self.comboBox_zbdumpChannel.setObjectName(_fromUtf8("comboBox_zbdumpChannel"))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.comboBox_zbdumpChannel.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(170, 190, 68, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_zbdumpCount = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_zbdumpCount.setGeometry(QtCore.QRect(250, 190, 111, 27))
        self.lineEdit_zbdumpCount.setObjectName(_fromUtf8("lineEdit_zbdumpCount"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(147, 240, 81, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_zbdumpOutput = QtGui.QLineEdit(self.frame_2)
        self.lineEdit_zbdumpOutput.setGeometry(QtCore.QRect(250, 240, 113, 27))
        self.lineEdit_zbdumpOutput.setObjectName(_fromUtf8("lineEdit_zbdumpOutput"))
        self.pushButton_zbdumpCapture = QtGui.QPushButton(self.frame_2)
        self.pushButton_zbdumpCapture.setGeometry(QtCore.QRect(240, 320, 141, 27))
        self.pushButton_zbdumpCapture.setCheckable(True)
        self.pushButton_zbdumpCapture.setObjectName(_fromUtf8("pushButton_zbdumpCapture"))
        self.tabWidget.addTab(self.zbdump, _fromUtf8(""))
        self.zbreplay = QtGui.QWidget()
        self.zbreplay.setObjectName(_fromUtf8("zbreplay"))
        self.tabWidget.addTab(self.zbreplay, _fromUtf8(""))
        self.zbpanidconflictflood = QtGui.QWidget()
        self.zbpanidconflictflood.setObjectName(_fromUtf8("zbpanidconflictflood"))
        self.tabWidget.addTab(self.zbpanidconflictflood, _fromUtf8(""))
        self.zborphannotify = QtGui.QWidget()
        self.zborphannotify.setObjectName(_fromUtf8("zborphannotify"))
        self.tabWidget.addTab(self.zborphannotify, _fromUtf8(""))
        self.zbrealign = QtGui.QWidget()
        self.zbrealign.setObjectName(_fromUtf8("zbrealign"))
        self.tabWidget.addTab(self.zbrealign, _fromUtf8(""))
        self.zbfakebeacon = QtGui.QWidget()
        self.zbfakebeacon.setObjectName(_fromUtf8("zbfakebeacon"))
        self.tabWidget.addTab(self.zbfakebeacon, _fromUtf8(""))
        self.zbopenear = QtGui.QWidget()
        self.zbopenear.setObjectName(_fromUtf8("zbopenear"))
        self.tabWidget.addTab(self.zbopenear, _fromUtf8(""))
        self.zbassocflood = QtGui.QWidget()
        self.zbassocflood.setObjectName(_fromUtf8("zbassocflood"))
        self.tabWidget.addTab(self.zbassocflood, _fromUtf8(""))
        self.zbconvert = QtGui.QWidget()
        self.zbconvert.setObjectName(_fromUtf8("zbconvert"))
        self.tabWidget.addTab(self.zbconvert, _fromUtf8(""))
        self.zbdsniff = QtGui.QWidget()
        self.zbdsniff.setObjectName(_fromUtf8("zbdsniff"))
        self.tabWidget.addTab(self.zbdsniff, _fromUtf8(""))
        self.zbgoodfind = QtGui.QWidget()
        self.zbgoodfind.setObjectName(_fromUtf8("zbgoodfind"))
        self.tabWidget.addTab(self.zbgoodfind, _fromUtf8(""))
        self.zbwardrive = QtGui.QWidget()
        self.zbwardrive.setObjectName(_fromUtf8("zbwardrive"))
        self.tabWidget.addTab(self.zbwardrive, _fromUtf8(""))
        self.zbscapy = QtGui.QWidget()
        self.zbscapy.setObjectName(_fromUtf8("zbscapy"))
        self.tabWidget.addTab(self.zbscapy, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionTools = QtGui.QAction(MainWindow)
        self.actionTools.setObjectName(_fromUtf8("actionTools"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionTools)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Attify Zigbee Exploitation Tool", None))
        __sortingEnabled = self.listWidget_zbid.isSortingEnabled()
        self.listWidget_zbid.setSortingEnabled(False)
        self.listWidget_zbid.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Device", None))
        self.label_2.setText(_translate("MainWindow", "Product String", None))
        self.label_3.setText(_translate("MainWindow", "Serial Number", None))
        self.pushButton_zbidRefresh.setText(_translate("MainWindow", "Refresh Devices", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbid), _translate("MainWindow", "zbid", None))
        self.pushButton_zbstmblrStart.setText(_translate("MainWindow", "Start", None))
        self.checkBox_zbstmblrVerbose.setText(_translate("MainWindow", "Verbose", None))
        self.comboBox_zbstmblrChannel.setItemText(0, _translate("MainWindow", "None", None))
        self.comboBox_zbstmblrChannel.setItemText(1, _translate("MainWindow", "16", None))
        self.comboBox_zbstmblrChannel.setItemText(2, _translate("MainWindow", "17", None))
        self.comboBox_zbstmblrChannel.setItemText(3, _translate("MainWindow", "18", None))
        self.comboBox_zbstmblrChannel.setItemText(4, _translate("MainWindow", "19", None))
        self.comboBox_zbstmblrChannel.setItemText(5, _translate("MainWindow", "20", None))
        self.comboBox_zbstmblrChannel.setItemText(6, _translate("MainWindow", "21", None))
        self.comboBox_zbstmblrChannel.setItemText(7, _translate("MainWindow", "22", None))
        self.comboBox_zbstmblrChannel.setItemText(8, _translate("MainWindow", "23", None))
        self.comboBox_zbstmblrChannel.setItemText(9, _translate("MainWindow", "24", None))
        self.comboBox_zbstmblrChannel.setItemText(10, _translate("MainWindow", "25", None))
        self.label_9.setText(_translate("MainWindow", "Channel (optional )", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbstumbler), _translate("MainWindow", "zbstumbler", None))
        self.pushButton_zbwsStart.setText(_translate("MainWindow", "Launch WireShark", None))
        self.comboBox_zbwsChannel.setItemText(0, _translate("MainWindow", "16", None))
        self.comboBox_zbwsChannel.setItemText(1, _translate("MainWindow", "17", None))
        self.comboBox_zbwsChannel.setItemText(2, _translate("MainWindow", "18", None))
        self.comboBox_zbwsChannel.setItemText(3, _translate("MainWindow", "19", None))
        self.comboBox_zbwsChannel.setItemText(4, _translate("MainWindow", "20", None))
        self.comboBox_zbwsChannel.setItemText(5, _translate("MainWindow", "21", None))
        self.comboBox_zbwsChannel.setItemText(6, _translate("MainWindow", "22", None))
        self.comboBox_zbwsChannel.setItemText(7, _translate("MainWindow", "23", None))
        self.comboBox_zbwsChannel.setItemText(8, _translate("MainWindow", "24", None))
        self.comboBox_zbwsChannel.setItemText(9, _translate("MainWindow", "25", None))
        self.label_10.setText(_translate("MainWindow", "Channel", None))
        self.label_8.setText(_translate("MainWindow", "Interface", None))
        self.label_11.setText(_translate("MainWindow", "   Count", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbwireshark), _translate("MainWindow", "zbwireshark", None))
        self.label_4.setText(_translate("MainWindow", "Interface", None))
        self.label_5.setText(_translate("MainWindow", "Channel", None))
        self.comboBox_zbdumpChannel.setItemText(0, _translate("MainWindow", "16", None))
        self.comboBox_zbdumpChannel.setItemText(1, _translate("MainWindow", "17", None))
        self.comboBox_zbdumpChannel.setItemText(2, _translate("MainWindow", "18", None))
        self.comboBox_zbdumpChannel.setItemText(3, _translate("MainWindow", "19", None))
        self.comboBox_zbdumpChannel.setItemText(4, _translate("MainWindow", "20", None))
        self.comboBox_zbdumpChannel.setItemText(5, _translate("MainWindow", "21", None))
        self.comboBox_zbdumpChannel.setItemText(6, _translate("MainWindow", "22", None))
        self.comboBox_zbdumpChannel.setItemText(7, _translate("MainWindow", "23", None))
        self.comboBox_zbdumpChannel.setItemText(8, _translate("MainWindow", "24", None))
        self.comboBox_zbdumpChannel.setItemText(9, _translate("MainWindow", "25", None))
        self.label_6.setText(_translate("MainWindow", "   Count", None))
        self.label_7.setText(_translate("MainWindow", "Output Fie", None))
        self.pushButton_zbdumpCapture.setText(_translate("MainWindow", "Start Capture", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbdump), _translate("MainWindow", "zbdump", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbreplay), _translate("MainWindow", "zbreplay", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbpanidconflictflood), _translate("MainWindow", "zbpanidconflictflood", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zborphannotify), _translate("MainWindow", "zborphannotify", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbrealign), _translate("MainWindow", "zbrealign", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbfakebeacon), _translate("MainWindow", "zbfakebeacon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbopenear), _translate("MainWindow", "zbopenear", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbassocflood), _translate("MainWindow", "zbassocflood", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbconvert), _translate("MainWindow", "zbconvert", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbdsniff), _translate("MainWindow", "zbdsniff", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbgoodfind), _translate("MainWindow", "zbgoodfind", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbwardrive), _translate("MainWindow", "zbwardrive", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zbscapy), _translate("MainWindow", "zbscapy", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuView.setTitle(_translate("MainWindow", "Settings", None))
        self.actionTools.setText(_translate("MainWindow", "Tools", None))
        self.actionTools.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+X", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

